---
- name: Make sure sgh dir exists
  file:
    path: "{{ SGH_HOME }}"
    state: directory
    owner: www-data
    group: www-data

- name: Unarchive SGH Front end
  unarchive: 
    src: "{{ FRONT_END_PATH }}front-end.tar.gz"
    dest: "{{ SGH_HOME }}"
    owner: www-data
    group: www-data
    mode: 0500
  register: jar_deployed

- name: copy properties for SGH
  template: 
    src: templates/nginx.conf.j2
    dest: "/etc/nginx/sites-enabled/sgh-front.conf"
    owner:  www-data
    group: www-data
    mode: 0644
  register: properties_updated

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
  when: ansible_service_mgr == "systemd"
