
enum EVOLUTION_CHART_COLORS {
	RED = '#F04848',
	YELLOW = '#FF8A00',
	GREEN = '#32C25B',
	BLACK = '#000000',
	BLUE = '#2687C5',
}

export enum LABELS {
	"p3" = 1,
	"p10",
	"p25",
	"p50",
	"p75",
	"p90",
	"p97",
	"s-3",
	"s-2",
	"s-1",
	"s0",
	"s1",
	"s2",
	"s3",
	"EVOLUTION"
}

export const CHARTS_LABELS_COLORS = {
	[LABELS.EVOLUTION]: EVOLUTION_CHART_COLORS.BLUE,
	[LABELS.p97]: EVOLUTION_CHART_COLORS.RED,
	[LABELS.p90]: EVOLUTION_CHART_COLORS.YELLOW,
	[LABELS.p75]: EVOLUTION_CHART_COLORS.YELLOW,
	[LABELS.p50]: EVOLUTION_CHART_COLORS.GREEN,
	[LABELS.p25]: EVOLUTION_CHART_COLORS.YELLOW,
	[LABELS.p10]: EVOLUTION_CHART_COLORS.YELLOW,
	[LABELS.p3]: EVOLUTION_CHART_COLORS.RED,
	[LABELS.s0]: EVOLUTION_CHART_COLORS.GREEN,
	[LABELS.s1]: EVOLUTION_CHART_COLORS.YELLOW,
	[LABELS.s2]: EVOLUTION_CHART_COLORS.RED,
	[LABELS["s-1"]]: EVOLUTION_CHART_COLORS.YELLOW,
	[LABELS["s-2"]]: EVOLUTION_CHART_COLORS.RED,
	[LABELS["s-3"]]: EVOLUTION_CHART_COLORS.BLACK,
	[LABELS.s3]: EVOLUTION_CHART_COLORS.BLACK,
}

export enum EVOLUTION_CHARTS  {
	HEIGHT_FOR_AGE = 1,
	WEIGHT_FOR_AGE,
	WEIGHT_FOR_LENGTH,
	WEIGHT_FOR_HEIGHT,
}

