
const ROOT = { role: 'ROOT', institutionId: -1 };
const ADMINISTRADOR = { role: 'ADMINISTRADOR', institutionId: -1 };
const ADMINISTRADOR_INSTITUCIONAL_BACKOFFICE = { role: 'ADMINISTRADOR_INSTITUCIONAL_BACKOFFICE' };

export { ROOT, ADMINISTRADOR, ADMINISTRADOR_INSTITUCIONAL_BACKOFFICE };