
const ROOT = { role: 'ROOT', institutionId: -1 };
const ADMINISTRADOR = { role: 'ADMINISTRADOR', institutionId: -1 };
const ADMINISTRADOR_INSTITUCIONAL_BACKOFFICE = { role: 'ADMINISTRADOR_INSTITUCIONAL_BACKOFFICE' };
const ADMINISTRADOR_DE_ACCESO_DOMINIO = { role: 'ADMINISTRADOR_DE_ACCESO_DOMINIO', institutionId: -1 };

export { ROOT, ADMINISTRADOR, ADMINISTRADOR_INSTITUCIONAL_BACKOFFICE, ADMINISTRADOR_DE_ACCESO_DOMINIO };