package net.pladema.edMonton.domain.exception;

public enum EdMontonEnumException {

	EDMONTON_TEST_ANSWER_LOST,

	EDMONTON_TEST_ANSWER_REPEATED,

	EDMONTON_TEST_ANSWER_NOT_EXISTS,

	EDMONTON_TEST_QUESTION_NOT_EXISTS,

	EDMONTON_TEST_QUESTION_ANSWER_NOT_VALID;
}
