stages:
  - build
  - dockerize
  - quality
  - publish-docker-image

include:
  - project: 'lamansys/cicd'
    file:
      - 'gitlab/stages/build-full.yml'
  - project: 'lamansys/cicd'
    file:
      - 'gitlab/stages/quality-backend.yml'

build_frontend:
  extends: .build_frontend_base
  cache:
    key:
      files:
        - front-end/apps/package-lock.json
        - front-end/backoffice/package-lock.json
    paths:
      - front-end/apps/node_modules
      - front-end/backoffice/node_modules

dockerize_snomed-schema:
  extends: .dockerize
  variables:
    IMAGE_TAG: ${CI_REGISTRY_IMAGE}/snomed-schema:$CI_COMMIT_REF_SLUG
    DOCKER_FOLDER: "dba/snomed-schema/"


publish_dockerhub_snomed-schema:
  extends: .dockerize_entrega
  variables:
    IMAGE_TAG: historiaclinica/snomed-schema:$CI_COMMIT_TAG
    DOCKER_FOLDER: "dba/snomed-schema/"
  rules:
    - if: '$CI_COMMIT_TAG'
      when: manual


code_freeze:
  stage: publish-docker-image
  image: bitnami/git:2.42.0
  script:
    - apt-get update
    - apt-get install -y maven
    - ./scripts/run-code-freeze.sh
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual

generar_release:
  stage: publish-docker-image
  image: bitnami/git:2.42.0
  script:
    - ./scripts/run-release.sh
  only:
    - /^rc-.*$/ 
  when: manual

