include:
  - project: 'lamansys/cicd'
    ref: gian
    file:
      - '/gitlab/integration.yml'

build_frontend:
  extends: .build_frontend_base
  cache:
    key:
      files:
        - front-end/apps/package-lock.json
        - front-end/backoffice/package-lock.json
    paths:
      - front-end/apps/node_modules
      - front-end/backoffice/node_modules

code_freeze:
  stage: publish-docker-image
  image: bitnami/git:2.42.0
  script:
    - apt-get update
    - apt-get install -y maven
    - ./scripts/run-code-freeze.sh
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PROJECT_ACCESS == "maintainer"'
      when: manual