version: '3'
services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: Local123
      POSTGRES_DB: hospitalDB
    volumes:
      - ./ci/dbapgsql/:/app/pg/
      - ./docker-data/postgres/:/data/
    ports:
      - "5432:5432"
