package net.pladema.clinichistory.requests.servicerequests.repository;

import net.pladema.clinichistory.requests.servicerequests.repository.entity.TranscribedServiceRequestDiagnosticReport;
import net.pladema.clinichistory.requests.servicerequests.repository.entity.TranscribedServiceRequestDiagnosticReportPK;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface TranscribedServiceRequestDiagnosticReportRepository extends JpaRepository<TranscribedServiceRequestDiagnosticReport, TranscribedServiceRequestDiagnosticReportPK> {
}
