package net.pladema.patient.application.port.exceptions;

public enum MergePatientExceptionEnum {

    PATIENT_NOT_EXISTS,
	ASSOCIATED_PERSON_NOT_FOUND,
	NULL_FIRST_NAME,
	NULL_LAST_NAME,
	NULL_IDENTIFICATION_TYPE,
	NULL_IDENTIFICATION_NUMBER,
	NULL_BIRTH_DATE,
	PATIENT_INACTIVE_NOT_EXISTS,

	MULTIPLE_INTERNMENT_EPISODES,
	MULTIPLE_EMERGENCY_CARE_EPISODES

}
