drop schema if exists commercial_medication cascade;
create schema commercial_medication;

set schema 'commercial_medication';

create table laboratory (
	id int primary key,
	description varchar(50) not null
);
create table sell_type (
	id int primary key,
	description varchar(50) not null
);
create table size (
	id int primary key,
	description varchar(50) not null
);
create table form (
	id int primary key,
	description varchar(50) not null
);
create table via (
	id int primary key,
	description varchar(50) not null
);
create table mono_drug (
	id int primary key,
	description varchar(50) not null
);
create table action (
	id int primary key,
	description varchar(50) not null
);
create table new_drug (
	id int primary key,
	description varchar(50) not null
);
create table potency (
	id int primary key,
	description varchar(50) not null
);
create table quantity (
	id int primary key,
	description varchar(50) not null
);
create table control (
	id int primary key,
	description varchar(50) not null
);
create table article (
	id int primary key,
	price numeric not null,
	price_validity_date date not null,
	name varchar(44) not null,
	presentation varchar(24) not null,
	laboratory_id int not null,
	troquel integer,
	presentation_status varchar(1) not null,
	is_imported varchar(1) not null,
	needs_fridge_preservation varchar(1) not null,
	iva varchar(1) not null,
	sell_type_id int not null,
	control_id int not null,
	size_id int not null,
	form_id int not null,
	via_id int not null,
	mono_drug_id int not null,
	action_id int not null,
	potency_value varchar not null,
	potency_id int not null,
	presentation_unit int not null,
	quantity_id int not null,
	gravamen varchar(1) not null,
	gluten_free varchar(1) not null,
	snomed_id varchar,
	prospect int
);

create table article_atc (
	article_id int not null,
	atc_id varchar not null,
	primary key(article_id, atc_id)
);

create table article_bar_code (
	article_id int not null,
	bar_code varchar not null,
	primary key(article_id, bar_code)
);
  
create table article_coverage (
	article_id int primary key,
	pami_ambulatory_percentage numeric,
	pami_sell_price numeric,
	sifar_coverage_brand varchar,
	ioma_fixed_value numeric,
	standardized_use_brand varchar
);

create table article_drug (
	article_id int not null,
	new_drug_id int not null,
	potency numeric,
	potency_id int,
	primary key(article_id, new_drug_id)
);

create table article_gtin (
	article_id int not null,
	gtin varchar not null,
	primary key(article_id, gtin)
);

create table atc (
	id varchar primary key,
	description varchar,
	comment varchar,
	daily_defined_dose numeric,
	unit varchar,
	administration_via varchar,
	daily_defined_dose_comment varchar,
	level varchar
);

create table update_log(
	id int primary key generated by default AS IDENTITY,
	log_id bigint not null,
	processed boolean not null
);

