package net.pladema.medicalconsultation.appointment.service.exceptions;

import lombok.Getter;

@Getter
public enum AppointmentEnumException {
	APPOINTMENT_ID_NOT_FOUND,
	TRANSITION_STATE_INVALID,
	ABSENT_REASON_REQUIRED,
	DIARY_PROFESSIONAL_INVALID,
	MISSING_DATA,
	WRONG_EMAIL_FORMAT,
	EXPIRED_APPOINTMENT_MISSING_REASON,
	EXPIRED_APPOINTMENT_MISSING_REASON_TEXT,
	EXPIRED_APPOINTMENT_INVALID_DATE_OR_HOUR
}
