package net.pladema.hl7.dataexchange.model.domain;

import lombok.Getter;
import lombok.Setter;
import net.pladema.hl7.dataexchange.model.adaptor.Cast;
import net.pladema.hl7.dataexchange.model.adaptor.FhirCode;
import net.pladema.hl7.dataexchange.model.adaptor.FhirID;
import net.pladema.hl7.foundation.lifecycle.ResourceStatus;
import org.apache.commons.collections4.BidiMap;
import org.apache.commons.collections4.bidimap.DualHashBidiMap;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Getter
@Setter
public class MedicationVo implements Serializable {

    private static final long serialVersionUID = -6874235756444884533L;

    private final BidiMap<Short, String> unitTimeCoding;

    public MedicationVo(){
        unitTimeCoding = new DualHashBidiMap<>();
        unitTimeCoding.put((short)1, "s");
        unitTimeCoding.put((short)2, "min");
        unitTimeCoding.put((short)3, "h");
        unitTimeCoding.put((short)4, "d");
        unitTimeCoding.put((short)5, "wk");
        unitTimeCoding.put((short)6, "mo");
        unitTimeCoding.put((short)7, "a");
    }

    public MedicationVo(Integer id, String sctidCode, String sctidTerm, String status,
                        Integer sequence, Integer timingRepeat, Double duration,
                        String durationUnit, Integer frequency, String periodUnit, Date startDate, Date endDate){
        this();
        setId(Cast.toString(id));
        setSctidCode(sctidCode);
        setSctidTerm(sctidTerm);
        setStatus(status);
        setStatementId(FhirID.autoGenerated());
        setDosage(new DosageVo(sequence, timingRepeat, duration, durationUnit, frequency, periodUnit));
        setEffectiveTimeStart(startDate);
        setEffectiveTimeEnd(endDate);
    }

    //====================Medication=====================
    private String id;

    //Medication info
    private String sctidCode;
    private String sctidTerm;

    //presentation of the medicinal product
    private String formCode;
    private String formTerm;

    private List<MedicationIngredientVo> ingredients = new ArrayList<>();

    //=====================Statement=====================
    private String statementId;

    private String status;

    private Date effectiveTimeStart;
    private Date effectiveTimeEnd;

    private DosageVo dosage;

    public FhirCode get() {
        return new FhirCode(sctidCode, sctidTerm);
    }

    public FhirCode getForm() {
        return new FhirCode(formCode, formTerm);
    }

    public String getStatus(){
        return ResourceStatus.getStatus(status);
    }
}
