package net.pladema.sisa.refeps.services.exceptions;

public enum RefepsExceptionsEnum {
	SNOWSTORM_TIMEOUT_SERVICE,
	SERVER_ERROR,
	NOT_FOUND,
	UNPARSEABLE_RESPONSE,
	BAD_REQUEST,
	API_TIMEOUT,
	NULL_RESPONSE,
	UNKNOWN_ERROR,
	UNPROCESSABLE_ENTITY,
	CANNOT_IDENTIFY_PROFESSIONAL,
	PROFESSIONAL_NOT_FOUND,
	GENERIC_ERROR,
	WRONG_STATE
}
