package net.pladema.hl7.dataexchange.exceptions;

import lombok.Getter;

@Getter
public enum DispenseValidationEnumException {

	TRANSITION_STATE_INVALID,
	PATIENT_DONT_MATCH,
	MEDICATION_DONT_MATCH,
	REQUEST_EXPIRED,
	REQUEST_CANCELED,
	NEGATIVE_QUANTITY,
	DATE_AFTER_TODAY,
	COVERAGE_NOT_MATCH,
	COVERAGE_AFFILIATE_NUMBER_DONT_MATCH,
	PRACTITIONER_NOT_MATCH,
	PRACTITIONER_CANT_BE_NULL,
	DISPENSE_RESOURCE_NOT_EXIST,
	DOSAGE_NOT_MATCH,
	DOSAGE_SEQUENCE_NOT_MATCH,
	DOSAGE_FREQUENCY_NOT_MATCH,
	DOSAGE_PERIOD_UNIT_NOT_MATCH

}
