package ar.lamansys.refcounterref.application.referenceforwarding.exceptions;

public enum ReferenceForwardingExceptionEnum {

	NULL_REFRENCE_ID,
	NULL_FORWARDING_ID,
	NULL_OBSERVATION,
	INVALID_REFERENCE_STATE,
	INVALID_ROLE,
	INVALID_USER,
	REGIONAL_FORWARDING_ALREADY_EXISTS,
	DOMAIN_FORWARDING_ALREADY_EXISTS,
	REFERENCE_HAS_CLOSURE
}
