package ar.lamansys.refcounterref.application.modifyReference.exceptions;

public enum ModifyReferenceExceptionEnum {

	INVALID_REFERENCE_ID,
	INVALID_USER_ID,
	INVALID_REFERENCE_REGULATION_STATE,
	INVALID_REFERENCE_STATUS,
	PRIORITY_REQUIRED,
	DESTINATION_INSTITUTION_REQUIRED,
	CLOSED_REFERENCE,
	HAS_APPOINTMENT

}
