package net.pladema.questionnaires.common.domain.exception;

public enum QuestionnaireEnumException {
	QUESTIONNAIRE_TEST_LOST_ANSWER,

	QUESTIONNAIRE_TEST_REPEATED_ANSWER,

	QUESTIONNAIRE_TEST_ANSWER_DOESNT_EXIST,

	QUESTIONNAIRE_TEST_QUESTION_DOESNT_EXIST,

	QUESTIONNAIRE_TEST_INVALID_QUESTION_ANSWER
}
