import { ERole } from '@api-rest/api-model';

export const ROLES_FOR_EDIT_DIAGNOSIS: ERole[] = [ERole.PROFESIONAL_DE_SALUD, ERole.ESPECIALISTA_EN_ODONTOLOGIA, ERole.ESPECIALISTA_MEDICO];

export const ROLES_FOR_ACCESS_MAIN: ERole[] = [ERole.PROFESIONAL_DE_SALUD, ERole.ESPECIALISTA_EN_ODONTOLOGIA];

