package ar.lamansys.refcounterref.application.createcounterreference.exceptions;

public enum CreateCounterReferenceExceptionEnum {

    INVALID_DOCTOR,
    NULL_PATIENT_ID,
    NULL_INSTITUTION_ID,
    NULL_CLINICAL_SPECIALTY_ID,
    NULL_COUNTER_REFERENCE_NOTE,
    INVALID_CLINICAL_SPECIALTY_ID,
    REPEATED_CONCEPTS,
	INVALID_REFERENCE,
	INVALID_REFERENCE_STATUS,
	INVALID_REFERENCE_REGULATION_STATE,
	CLOSED_REFERENCE;

}