package net.pladema.medicalconsultation.virtualConsultation.application.changeResponsibleProfessionalAvailability;

import net.pladema.medicalconsultation.virtualConsultation.domain.VirtualConsultationResponsibleProfessionalAvailabilityBo;

public interface ChangeResponsibleProfessionalAvailabilityService {

	boolean run(VirtualConsultationResponsibleProfessionalAvailabilityBo responsibleAvailability);

}
