import { ERole } from "@api-rest/api-model";

export enum Tabs {
	PROFESSIONAL = 'OFERTA POR PROFESIONAL',
	INSTITUTION = 'OFERTA EN INSTITUCIÓN',
	CARE_NETWORK = 'OFERTA EN RED DE ATENCIÓN',
	IMAGE_NETWORK = 'DIAGNÓSTICO POR IMÁGENES',
	REPORT = 'SOLICITUDES'
}

const HEALTH_PROFESSIONAL_TABS = [Tabs.PROFESSIONAL, Tabs.CARE_NETWORK, Tabs.REPORT];

export const ROLE_TABS = {
	[ERole.ADMINISTRATIVO]: [Tabs.PROFESSIONAL, Tabs.INSTITUTION, Tabs.CARE_NETWORK, Tabs.REPORT],
	[ERole.ESPECIALISTA_MEDICO]: HEALTH_PROFESSIONAL_TABS,
	[ERole.PROFESIONAL_DE_SALUD]: HEALTH_PROFESSIONAL_TABS,
    [ERole.ESPECIALISTA_EN_ODONTOLOGIA]: HEALTH_PROFESSIONAL_TABS,
	[ERole.ENFERMERO]: [Tabs.PROFESSIONAL],
	[ERole.ADMINISTRATIVO_RED_DE_IMAGENES]: [Tabs.IMAGE_NETWORK],
	[ERole.ADMINISTRADOR_AGENDA]: [Tabs.PROFESSIONAL, Tabs.IMAGE_NETWORK],
}
