package net.pladema.medicalconsultation.diary.service.exception;

public enum DiaryEnumException {
	PREDECESSOR_PROFESSIONAL_WITHOUT_HIERARCHICAL_UNIT,
	MODALITY_NOT_FOUND,
	SEARCH_CRITERIA_NOT_FOUND,
	DIARY_OPENING_HOURS_OVERLAP,
	DOCTORS_OFFICE_NOT_FOUND,
}
