export enum  EmergencyCareType {
	ADULTO = 1,
	PEDIATRICO = 2,
	GINECOLOGIA_OBSTETRICIA = 3
}

export enum EmergencyCareEntranceType {
	CAMINANDO = 1,
	SILLA_RUEDAS = 2,
	AMBULANCIA_SIN_MEDICO = 3,
	AMBULANCIA_CON_MEDICO = 4
}

export enum DischargeTypes {
	ALTA_MEDICA = 1,
	TRASLADO_A_OTRO_ESTABLECIMIENTO = 2,
	DEFUNCION = 3,
	RETIRO_VOLUNTARIO = 4,
	OTRO = 5,
	CANCELANCION = 6,
	SUSPENCION = 7,
	TRASLADO_A_OTRO_HOSPITAL = 8,
	TRASLADO_A_TERCER_NIVEL = 9,
	TRASLADO_A_OTRO_TIPO_DE_INSTITUCION = 10,
	ALTA_A_INTERNACION = 11,
	ALTA_A_INTERNACION_DOMICILIARIA = 12,
	ALTA_A_SEGUIMIENTO_DOMICILIARIO = 13,
}
