//
// Autogenerated ID
//
package net.pladema.hl7.dataexchange.model.adaptor;

import java.util.UUID;

public class FhirID {

    public static String autoGenerated() {
        return UUID.randomUUID().toString();
    }

}
