//
// Autogenerated ID
//
package net.pladema.hl7.dataexchange.model.adaptor;

import lombok.experimental.UtilityClass;

import java.util.UUID;

@UtilityClass
public class FhirID {

    public static String autoGenerated() {
        return UUID.randomUUID().toString();
    }

}
