package net.pladema.permissions.repository.enums;

import ar.lamansys.sgx.shared.exceptions.NotFoundException;

public enum ERole {

	ROOT(1, "ROOT", ERoleLevel.LEVEL0),
	ADMINISTRADOR(2, "ADMINISTRADOR", ERoleLevel.LEVEL0),
	ESPECIALISTA_MEDICO(3, "ESPECIALISTA_MEDICO", ERoleLevel.LEVEL1),
	PROFESIONAL_DE_SALUD(4, "PROFESIONAL_DE_SALUD", ERoleLevel.LEVEL1),
	ADMINISTRATIVO(5, "ADMINISTRATIVO", ERoleLevel.LEVEL1),
	ENFERMERO_ADULTO_MAYOR(6, "ENFERMERO_ADULTO_MAYOR", ERoleLevel.LEVEL1),
	ENFERMERO(7,"ENFERMERO",ERoleLevel.LEVEL1),
	ADMINISTRADOR_INSTITUCIONAL_BACKOFFICE(8,"ADMINISTRADOR_INSTITUCIONAL_BACKOFFICE", ERoleLevel.LEVEL1),
	ADMINISTRADOR_AGENDA(9,"ADMINISTRADOR_AGENDA", ERoleLevel.LEVEL1),
	API_CONSUMER(10, "API_CONSUMER", ERoleLevel.LEVEL0),
	ESPECIALISTA_EN_ODONTOLOGIA(11, "ESPECIALISTA_EN_ODONTOLOGIA", ERoleLevel.LEVEL1),
	ADMINISTRADOR_DE_CAMAS(12, "ADMINISTRADOR_DE_CAMAS", ERoleLevel.LEVEL1),
	PERSONAL_DE_IMAGENES(13, "PERSONAL_DE_IMAGENES", ERoleLevel.LEVEL1),
	PERSONAL_DE_LABORATORIO(14, "PERSONAL_DE_LABORATORIO", ERoleLevel.LEVEL1),
	PERSONAL_DE_FARMACIA(15, "PERSONAL_DE_FARMACIA", ERoleLevel.LEVEL1),
	PERSONAL_DE_ESTADISTICA(16, "PERSONAL_DE_ESTADISTICA", ERoleLevel.LEVEL1),
	PARTIALLY_AUTHENTICATED(17, "PARTIALLY_AUTHENTICATED", ERoleLevel.LEVEL0),
	PERFIL_EPIDEMIO_MESO(18, "PERFIL_EPIDEMIO_MESO", ERoleLevel.LEVEL0),
	PERFIL_EPIDEMIO_INSTITUCION(19, "PERFIL_EPIDEMIO_INSTITUCION", ERoleLevel.LEVEL1),
	ADMINISTRATIVO_RED_DE_IMAGENES(20,"ADMINISTRATIVO_RED_DE_IMAGENES", ERoleLevel.LEVEL1),
	PRESCRIPTOR(21, "PRESCRIPTOR", ERoleLevel.LEVEL1),
	ADMINISTRADOR_INSTITUCIONAL_PRESCRIPTOR(22, "ADMINISTRADOR_INSTITUCIONAL_PRESCRIPTOR", ERoleLevel.LEVEL1),
	AUDITOR_MPI(23,"AUDITOR_MPI", ERoleLevel.LEVEL0),
	TECNICO(24, "TECNICO", ERoleLevel.LEVEL1),
	PERSONAL_DE_LEGALES(25, "PERSONAL_DE_LEGALES", ERoleLevel.LEVEL1),
	INFORMADOR(26, "INFORMADOR", ERoleLevel.LEVEL1),

	API_FACTURACION(27, "API_FACTURACION", ERoleLevel.LEVEL1),
	API_TURNOS(28, "API_TURNOS", ERoleLevel.LEVEL1),
	API_PACIENTES(29, "API_PACIENTES", ERoleLevel.LEVEL0),
	API_RECETAS(30, "API_RECETAS", ERoleLevel.LEVEL0),
	API_SIPPLUS(31, "API_SIPPLUS", ERoleLevel.LEVEL0),
	API_USERS(32, "API_USERS", ERoleLevel.LEVEL0),
	VIRTUAL_CONSULTATION_PROFESSIONAL(33, "VIRTUAL_CONSULTATION_PROFESSIONAL", ERoleLevel.LEVEL1),
	VIRTUAL_CONSULTATION_RESPONSIBLE(34, "VIRTUAL_CONSULTATION_RESPONSIBLE", ERoleLevel.LEVEL1),
	API_IMAGENES(35, "API_IMAGENES", ERoleLevel.LEVEL0),
	API_ORQUESTADOR(36, "API_ORQUESTADOR", ERoleLevel.LEVEL1),
	ADMINISTRADOR_DE_ACCESO_DOMINIO(37, "ADMINISTRADOR_DE_ACCESO_DOMINIO", ERoleLevel.LEVEL0),
	GESTOR_DE_ACCESO_DE_DOMINIO(38, "GESTOR_DE_ACCESO_DE_DOMINIO", ERoleLevel.LEVEL0),
	GESTOR_DE_ACCESO_LOCAL(39, "GESTOR_DE_ACCESO_LOCAL", ERoleLevel.LEVEL0),
	GESTOR_DE_ACCESO_REGIONAL(40, "GESTOR_DE_ACCESO_REGIONAL", ERoleLevel.LEVEL0),
	ABORDAJE_VIOLENCIAS(41, "ABORDAJE_VIOLENCIAS", ERoleLevel.LEVEL1),
	AUDITORIA_DE_ACCESO(42,"AUDITORIA_DE_ACCESO",ERoleLevel.LEVEL0),
	GESTOR_CENTRO_LLAMADO(43, "GESTOR_CENTRO_LLAMADO", ERoleLevel.LEVEL0),
	ADMINISTRADOR_DE_DATOS_PERSONALES(44, "ADMINISTRADOR_DE_DATOS_PERSONALES", ERoleLevel.LEVEL0),
	FHIR_POST_DIAGNOSTIC_REPORT(45, "FHIR_POST_DIAGNOSTIC_REPORT", ERoleLevel.LEVEL0),
	FHIR_ACCESS_ALL_RESOURCES(46, "FHIR_ACCESS_ALL", ERoleLevel.LEVEL0),
	API_ANEXO(47, "API_ANEXO", ERoleLevel.LEVEL1),
	API_REPORTES(48, "API REPORTES", ERoleLevel.LEVEL0)
	;

	private Short id;
	private String value;
	private ERoleLevel level;
 
	ERole(Number id, String value, ERoleLevel level) {
		this.id = id.shortValue();
		this.value = value;
		this.level = level;
	}
 
	public String getValue() {
		return value;
	}
	public Short getId() {
		return id;
	}
	public ERoleLevel getLevel() {
		return level;
	}

	public static ERole map(java.lang.Short id) {
		for(ERole e : values()) {
			if(e.id.equals(id)) return e;
		}
		throw new NotFoundException("role-not-exists", String.format("El rol %s no existe", id));
	}

	public static ERole map(java.lang.String value) {
		for(ERole e : values()) {
			if(e.value.equals(value)) return e;
		}
		throw new NotFoundException("role-not-exists", String.format("El rol %s no existe", value));
	}

}
